version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-loja
    restart: always
    environment:
      MYSQL_DATABASE: loja_sapato
      MYSQL_USER: myuser
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: verysecret
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
